sudo: required
services:
  - docker

before_install:
  - docker build -t gideonflash/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gideonflash/react-test npm test

after_success:
  - docker build -t gideonflash/multi-client ./client
  - docker build -t gideonflash/multi-nginx ./nginx
  - docker build -t gideonflash/multi-server ./server
  - docker build -t gideonflash/multi-worker ./worker
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push gideonflash/multi-client
  - docker push gideonflash/multi-nginx
  - docker push gideonflash/multi-server
  - docker push gideonflash/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: elasticbeanstalk-eu-west-2-862366749678
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
